#!/bin/python3

import sys
right_value= 0
n = int(input().strip())
a = []
final = 0
values = 0
for a_i in range(n):
   a_t = [int(a_temp) for a_temp in input().strip().split(' ')]
   a.append(a_t)
for i in range(len(a)):
    values =values + a[i][i] 
for i in range(len(a)):    
    l = len(a[i]) - (i+1)
    right_value = right_value + a[i][l]
   
final = abs(values- right_value)
print (final)
